version: '3'

version: '3.4'
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file
services:
   
  #nginx:
  #  container_name: nginx_container
  #  image: nginx
  #  ports:
  #    - "80:80"
  #  restart: unless-stopped
  #  volumes:
  #    - $PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf           
  #    - $PWD/nginx/logs/:/var/log/nginx/
  #    - $PWD/nginx/data/:/var/share/nginx/html/ 
  # 
  xxl_job:
    container_name: xxl_job_container
    image: xuxueli/xxl-job-admin:2.1.1
    ports:
      - "9091:8080"
    restart: unless-stopped
    environment:
      spring.datasource.url: jdbc:mysql://218.104.238.196:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 
      spring.datasource.username: root 
      spring.datasource.password: yourpass123456
    volumes:
      - $PWD/xxl_job/data/applogs:/tmp
  zoo1:
    image: zookeeper
    logging: *default-logging
    restart: unless-stopped
    hostname: zoo1
    ports:
    - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/zookeeper/data/zoo1/data:/data
      - $PWD/zookeeper/data/zoo1/datalog:/datalog
      - $PWD/zookeeper/conf/zoo1:/conf
      
    